# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Airport_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=200, null=True)),
                ('airport_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Airport_Details',
                'verbose_name_plural': 'Airport_Details',
            },
        ),
        migrations.CreateModel(
            name='City_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'City_Master',
                'verbose_name_plural': 'City_Master',
            },
        ),
        migrations.CreateModel(
            name='Country_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Country_Master',
                'verbose_name_plural': 'Country_Master',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('emal_id', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'User_Details',
                'verbose_name_plural': 'User_Details',
            },
        ),
        migrations.AddField(
            model_name='city_master',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.Country_Master'),
        ),
        migrations.AddField(
            model_name='airport_details',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.Country_Master'),
        ),
    ]
