# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-15 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
    ]
