# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-16 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0002_auto_20200415_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='moto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='residence_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='travel_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
