# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0003_auto_20200416_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_Code_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('dial_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='fk_dialcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.Country_Code_Master'),
        ),
    ]
