# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-17 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0004_auto_20200416_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport_details',
            name='city_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
