# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0005_auto_20200417_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_code_master',
            old_name='name',
            new_name='capital_name',
        ),
        migrations.AddField(
            model_name='country_code_master',
            name='country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country_code_master',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
