# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0007_auto_20200421_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='Profile_Image/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='Profile_Image/')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='Profile_Image/')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='Profile_Image/')),
                ('image_five', models.ImageField(blank=True, null=True, upload_to='Profile_Image/')),
                ('moto', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('travel_country', models.CharField(blank=True, max_length=200, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.User_Details')),
                ('residence_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.Country_Code_Master')),
            ],
            options={
                'verbose_name': 'Personal_Details',
                'verbose_name_plural': 'Personal_Details',
            },
        ),
    ]
