# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0008_personal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='fk_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_name_p', to='Pairport_Dev_App.Country_Code_Master'),
        ),
    ]
