# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0009_user_details_fk_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='image_five',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='moto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='residence_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='travel_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
