# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0010_auto_20200421_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_layover', models.DateField(blank=True, null=True)),
                ('arival_time', models.TimeField(blank=True, null=True)),
                ('layover_time', models.TimeField(blank=True, null=True)),
                ('fk_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.Airport_Details')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.User_Details')),
            ],
            options={
                'verbose_name_plural': 'Trip_Details',
                'verbose_name': 'Trip_Details',
            },
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='fk_user',
        ),
        migrations.RemoveField(
            model_name='personal_details',
            name='residence_country',
        ),
        migrations.DeleteModel(
            name='Personal_Details',
        ),
    ]
