# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0011_auto_20200423_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_details',
            name='layover_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
