# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0012_auto_20200423_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='insta_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
