# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-24 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0013_user_details_insta_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='residence_country',
        ),
        migrations.AddField(
            model_name='user_details',
            name='selected_country_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
