# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-25 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0014_auto_20200424_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'ChatChild',
                'verbose_name': 'ChatChild',
            },
        ),
        migrations.CreateModel(
            name='ChatMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.CharField(blank=True, max_length=10, null=True)),
                ('user2_id', models.CharField(blank=True, max_length=10, null=True)),
                ('fk_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.Trip_Details')),
            ],
            options={
                'verbose_name_plural': 'ChatMaster',
                'verbose_name': 'ChatMaster',
            },
        ),
        migrations.AddField(
            model_name='chatchild',
            name='fk_chat_master',
            field=models.ForeignKey(db_column='fk_chat_master', null=True, on_delete=django.db.models.deletion.CASCADE, to='Pairport_Dev_App.ChatMaster'),
        ),
    ]
