# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0015_auto_20200425_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_country_name', models.CharField(blank=True, max_length=200, null=True)),
                ('flag_images', models.ImageField(blank=True, null=True, upload_to='Flag_Image/')),
            ],
            options={
                'verbose_name_plural': 'Flags_Details',
                'verbose_name': 'Flags_Details',
            },
        ),
    ]
