# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0016_flags_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags_details',
            name='flag_country_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
