# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pairport_Dev_App', '0018_auto_20200429_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='flags_details',
            name='flag_imagesss',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
